version: '1.0'

stages:
- test
- publish

steps:

  unitTest:
    title: Running Unit tests
    stage: test
    image: node:10-jessie
    commands:
    - npm install
    - npm test

  publish:
    title: Publish sygaldry-core
    stage: publish
    image: node:10-jessie
    when:
      branch:
        only:
        - master
    commands:
    - scripts/npm-login.sh ${NPM_TOKEN}
    - npm publish
