stages:
- name: build
  runes:
  - definition: MavenRune
    mavenHome: ~/.m2
    stages: clean install
    version: 3.5.0-jdk-8-slim
    opts:
  - definition: DockerRune
    version: latest
    command: build
    args:
    - -t docker.io/sygaldry-demos/springboot:latest
  - definition: DockerRune
    version: latest
    command: push
    args:
    - docker.io/sygaldry-demos/springboot:latest
- name: deploy
  runes:
  - definition: TerraformRune
    terraformFolder: infrastructure
    tfvars:
    - infrastructure/dev.tfvars
